name: extended_bloc
description: >
  A predictable state management library that helps implement the BLoC design pattern.
version: 7.0.0-dev
repository: https://github.com/PlugFox/extended_bloc/tree/master
issue_tracker: https://github.com/PlugFox/extended_bloc/issues
homepage: https://github.com/PlugFox/extended_bloc
#authors:
#  - Plague Fox <plugfox@gmail.com>
#documentation: https://pub.dev/documentation/extended_bloc/latest

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  bloc: ^7.0.0

dev_dependencies:
  bloc_test: ^8.0.1
  test: ^1.14.6
  coverage: '>=0.14.2 <2.0.0'